version: '3.7'
services:

  try-to-sqlalchemy:
    build:
      context: ./try-to-sqlalchemy
    container_name: try-to-sqlalchemy
    command: bash
    tty: true
    volumes:
      - ./try-to-sqlalchemy:/var/try-to-SqlAlchemy
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.16
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    